
  # postgresql docker file  


from postgres:17


label maintaner = "naser.mortezaee"
label version = '1.0'
label description = 'costomize postgresql 17 image'

# databas configuration
env postgres_db = nanidb
env postgres_user = admin
env postgres_password = admin@123

#timezone
env tz = Asia/Tehran


#postgresql_port
expose 5432


