	
	# mongodb Dockerfile 

FROM mongo:7

# add label for configuration
LABEL maintainer="naser.mortezaee"
LABEL version="1.0"
LABEL description="customized mysql latest"


# database configuration
ENV MONGO_INITDB_ROOT_USERNAME = admin
ENV MONGO_INITDB_ROOT_PASSWORD=admin@123

# port MongoDB
expose 27017
